apiVersion: v1
kind: Service
metadata:
  name: admission-webhook-demo-svc
  labels:
    app: admission-webhook-demo
spec:
  ports:
  - port: 443
    targetPort: 8443
  selector:
    app: admission-webhook-demo
